Traceback (most recent call last):
  File "/home/gasser/anaconda3/envs/serab/lib/python3.8/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/gasser/anaconda3/envs/serab/lib/python3.8/site-packages/nbclient/client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/gasser/anaconda3/envs/serab/lib/python3.8/site-packages/nbclient/util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/gasser/anaconda3/envs/serab/lib/python3.8/site-packages/nbclient/util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "/home/gasser/anaconda3/envs/serab/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/gasser/anaconda3/envs/serab/lib/python3.8/site-packages/nbclient/client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "/home/gasser/anaconda3/envs/serab/lib/python3.8/site-packages/nbclient/client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/home/gasser/anaconda3/envs/serab/lib/python3.8/site-packages/nbclient/client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#read wav files' paths
wav_dirs = sorted(glob('datasets/scripted_spont_dataset/preprocessed_audios_dur3sec/*'))
wav_files = sorted(glob('datasets/scripted_spont_dataset/preprocessed_audios_dur3sec/*/*.wav'))
print(f'{len(wav_files)} samples')
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Input [0;32mIn [1][0m, in [0;36m<cell line: 2>[0;34m()[0m
[1;32m      1[0m [38;5;66;03m#read wav files' paths[39;00m
[0;32m----> 2[0m wav_dirs [38;5;241m=[39m [38;5;28msorted[39m([43mglob[49m([38;5;124m'[39m[38;5;124mdatasets/scripted_spont_dataset/preprocessed_audios_dur3sec/*[39m[38;5;124m'[39m))
[1;32m      3[0m wav_files [38;5;241m=[39m [38;5;28msorted[39m(glob([38;5;124m'[39m[38;5;124mdatasets/scripted_spont_dataset/preprocessed_audios_dur3sec/*/*.wav[39m[38;5;124m'[39m))
[1;32m      4[0m [38;5;28mprint[39m([38;5;124mf[39m[38;5;124m'[39m[38;5;132;01m{[39;00m[38;5;28mlen[39m(wav_files)[38;5;132;01m}[39;00m[38;5;124m samples[39m[38;5;124m'[39m)

[0;31mNameError[0m: name 'glob' is not defined
NameError: name 'glob' is not defined

